





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.DatedContent
{
	public static partial class _Content_Date_Constants{

			public const string TemplateIdString = "25a16898-b5b1-49c1-955f-6a4c897f058c";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Content Date";

					
			public static readonly Guid Content_Date_FieldId = new Guid("3a75a937-d8ce-4970-b0e3-11e8a6ba9943");
			public const string Content_Date_FieldName = "Content Date";
			
			

	}


}
namespace Foundation.DatedContent
{
	public static partial class _Content_Datetime_Constants{

			public const string TemplateIdString = "e0a4c51c-cb7c-4ad9-a817-5584de005771";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Content Datetime";

					
			public static readonly Guid Content_Datetime_FieldId = new Guid("228ca676-1ea0-4abe-b83a-6ec9071c41c4");
			public const string Content_Datetime_FieldName = "Content Datetime";
			
			

	}


}
