





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.Events
{
	public static partial class _Event_Detail_Page_Type_Constants{

			public const string TemplateIdString = "efa4d9ed-af70-43b9-b7d7-481fae4142e5";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Event Detail Page Type";

					
			public static readonly Guid Content_Datetime_FieldId = new Guid("228ca676-1ea0-4abe-b83a-6ec9071c41c4");
			public const string Content_Datetime_FieldName = "Content Datetime";
			
			

	}


}
