





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.GenericJumbotron
{
	public static partial class Generic_Jumbotrons_Folder_Constants{

			public const string TemplateIdString = "64f84d8f-54f4-4dd4-9caa-13b21e34cc47";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Jumbotrons Folder";

			

	}


}
namespace Feature.GenericJumbotron
{
	public static partial class Generic_Jumbotron_Constants{

			public const string TemplateIdString = "c8b43f79-40de-4365-9fa0-b4de827ac207";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Jumbotron";

					
			public static readonly Guid Image_FieldId = new Guid("41e1c3bd-1a48-40b6-a4e6-edaa845ffe9f");
			public const string Image_FieldName = "Image";
			
			

	}


}
