





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.Events
{
	public static partial class Events_Listing_Constants{

			public const string TemplateIdString = "16b5e79c-012e-4928-8514-840a5c16a205";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Events Listing";

			

	}


}
