





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace ORMless.Feature.GenericCallout
{
	public static partial class Generic_Callout_Constants{

			public const string TemplateIdString = "02a52302-32f0-4860-8156-f4dcd7515c35";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Callout";

					
			public static readonly Guid Date_FieldId = new Guid("1a5acd07-b6d9-4439-a2b1-c356c2542de2");
			public const string Date_FieldName = "Date";
			
					
			public static readonly Guid Datetime_FieldId = new Guid("31f4e463-0ec5-4868-8b56-bfeefe7a3a3d");
			public const string Datetime_FieldName = "Datetime";
			
					
			public static readonly Guid Description_FieldId = new Guid("4a70c2b9-747e-497c-a9bf-5b4bc6c5f0e6");
			public const string Description_FieldName = "Description";
			
					
			public static readonly Guid General_Link_FieldId = new Guid("907e5b21-aa60-47c9-b654-afa47bd4fa77");
			public const string General_Link_FieldName = "General Link";
			
					
			public static readonly Guid Title_FieldId = new Guid("6f26c996-06b8-44c0-9094-03b796112b8e");
			public const string Title_FieldName = "Title";
			
			

	}


}
namespace ORMless.Feature.GenericCallout
{
	public static partial class Generic_Callout_Rendering_Parameters_Constants{

			public const string TemplateIdString = "30c519e7-9f11-4207-94f2-e73083ccc61d";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Callout Rendering Parameters";

					
			public static readonly Guid Background_Color_FieldId = new Guid("12a53c5f-49ff-44c8-9aae-692f369c850f");
			public const string Background_Color_FieldName = "Background Color";
			
			

	}


}
namespace ORMless.Feature.GenericCallout
{
	public static partial class Generic_Callouts_Folder_Constants{

			public const string TemplateIdString = "96902c24-1f0e-49ce-be60-a842275f3507";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Callouts Folder";

			

	}


}
