





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.NavigationLink
{
	public static partial class _Navigation_Link_Constants{

			public const string TemplateIdString = "29f71a34-5737-4c6e-a63c-cfc75274f692";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Navigation Link";

					
			public static readonly Guid Link_Text_FieldId = new Guid("590acc35-dff5-4e3e-af84-9e744a0c2a38");
			public const string Link_Text_FieldName = "Link Text";
			
					
			public static readonly Guid Link_FieldId = new Guid("f2baa69e-41ef-4a1c-ae55-d2ed60e0f7fc");
			public const string Link_FieldName = "Link";
			
			

	}


}
