





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.TextContent
{
	public static partial class _Content_Title_Constants{

			public const string TemplateIdString = "9198d02b-e1be-4712-9d95-7bbef68f6a7e";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Content Title";

					
			public static readonly Guid Content_Title_FieldId = new Guid("c51e85d9-8016-44ea-8038-28d1a1f3c524");
			public const string Content_Title_FieldName = "Content Title";
			
			

	}


}
namespace Foundation.TextContent
{
	public static partial class _Content_Rich_Description_Constants{

			public const string TemplateIdString = "b699d5cc-cb3f-4179-b6f1-1a461ab11e92";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Content Rich Description";

					
			public static readonly Guid Content_Rich_Description_FieldId = new Guid("38dfb242-21ad-4ed8-ba28-e820d09f4539");
			public const string Content_Rich_Description_FieldName = "Content Rich Description";
			
			

	}


}
namespace Foundation.TextContent
{
	public static partial class _Content_Simple_Description_Constants{

			public const string TemplateIdString = "bf5291ac-db7c-401f-9f75-1b93f441b3de";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Content Simple Description";

					
			public static readonly Guid Content_Simple_Description_FieldId = new Guid("5a2bd0dd-e068-400d-9141-22923a762697");
			public const string Content_Simple_Description_FieldName = "Content Simple Description";
			
			

	}


}
