





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.SharedContent
{
	public static partial class Shared_Content_Folder_Constants{

			public const string TemplateIdString = "5c2caa3b-8b94-4c31-946c-36368ff4ebb4";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Shared Content Folder";

			

	}


}
