





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.GenericCard
{
	public static partial class Generic_Card_Constants{

			public const string TemplateIdString = "02a52302-32f0-4860-8156-f4dcd7515c35";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Card";

					
			public static readonly Guid Image_FieldId = new Guid("a24220fa-0377-41e3-b899-fc6273b4264b");
			public const string Image_FieldName = "Image";
			
					
			public static readonly Guid Link_Text_FieldId = new Guid("590acc35-dff5-4e3e-af84-9e744a0c2a38");
			public const string Link_Text_FieldName = "Link Text";
			
					
			public static readonly Guid Link_FieldId = new Guid("f2baa69e-41ef-4a1c-ae55-d2ed60e0f7fc");
			public const string Link_FieldName = "Link";
			
					
			public static readonly Guid Content_Simple_Description_FieldId = new Guid("5a2bd0dd-e068-400d-9141-22923a762697");
			public const string Content_Simple_Description_FieldName = "Content Simple Description";
			
					
			public static readonly Guid Content_Title_FieldId = new Guid("c51e85d9-8016-44ea-8038-28d1a1f3c524");
			public const string Content_Title_FieldName = "Content Title";
			
			

	}


}
namespace Feature.GenericCard
{
	public static partial class Generic_Card_Rendering_Parameters_Constants{

			public const string TemplateIdString = "30c519e7-9f11-4207-94f2-e73083ccc61d";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Card Rendering Parameters";

					
			public static readonly Guid Background_Color_FieldId = new Guid("12a53c5f-49ff-44c8-9aae-692f369c850f");
			public const string Background_Color_FieldName = "Background Color";
			
			

	}


}
namespace Feature.GenericCard
{
	public static partial class Generic_Cards_Callouts_Folder_Constants{

			public const string TemplateIdString = "96902c24-1f0e-49ce-be60-a842275f3507";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Cards Callouts Folder";

			

	}


}
