





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.Publications
{
	public static partial class _Related_Publications_Constants{

			public const string TemplateIdString = "0ec0d35c-5038-4577-bd0f-48538bf50d5a";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Related Publications";

					
			public static readonly Guid Related_Publications_FieldId = new Guid("9ab4865f-766c-4348-9368-c6033d6fb210");
			public const string Related_Publications_FieldName = "Related Publications";
			
			

	}


}
namespace Foundation.Publications
{
	public static partial class _Publication_Detail_Page_Type_Constants{

			public const string TemplateIdString = "844d69a3-9eae-44e3-8764-2ec5514d06b4";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Publication Detail Page Type";

			

	}


}
