





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.Site
{
	public static partial class Site_Constants{

			public const string TemplateIdString = "9b06714d-96e7-4299-ac62-ce0d92d253b7";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Site";

			

	}


}
