





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.GlobalHeader
{
	public static partial class Global_Headers_Folder_Constants{

			public const string TemplateIdString = "22ff0401-6ce6-4f9d-8ebf-6ae31e882639";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Global Headers Folder";

			

	}


}
namespace Feature.GlobalHeader
{
	public static partial class Header_Navigation_Link_Constants{

			public const string TemplateIdString = "518e417c-b405-4ac8-97a0-6ce516ab6977";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Header Navigation Link";

					
			public static readonly Guid Link_Text_FieldId = new Guid("590acc35-dff5-4e3e-af84-9e744a0c2a38");
			public const string Link_Text_FieldName = "Link Text";
			
					
			public static readonly Guid Link_FieldId = new Guid("f2baa69e-41ef-4a1c-ae55-d2ed60e0f7fc");
			public const string Link_FieldName = "Link";
			
			

	}


}
namespace Feature.GlobalHeader
{
	public static partial class Global_Header_Constants{

			public const string TemplateIdString = "a7e5cf90-e5a3-4033-8dd4-82ffce20c659";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Global Header";

					
			public static readonly Guid Logo_Link_FieldId = new Guid("cf339df8-c6a4-454c-ab1f-905def08e343");
			public const string Logo_Link_FieldName = "Logo Link";
			
					
			public static readonly Guid Logo_FieldId = new Guid("c67b6c8b-7636-4624-95de-bd2f80bf6918");
			public const string Logo_FieldName = "Logo";
			
			

	}


}
