





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.GlobalSearch
{
	public static partial class Global_Search_Constants{

			public const string TemplateIdString = "92329143-a77d-4a52-85b6-0bda30e92b19";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Global Search";

					
			public static readonly Guid Keywords_Textbox_Watermark_FieldId = new Guid("7460ad08-5b20-4a3a-beac-5c0c2872674e");
			public const string Keywords_Textbox_Watermark_FieldName = "Keywords Textbox Watermark";
			
					
			public static readonly Guid Results_Section_Title_FieldId = new Guid("8b4b4f68-1229-4c53-9117-4d587f32b8cf");
			public const string Results_Section_Title_FieldName = "Results Section Title";
			
					
			public static readonly Guid Submit_Button_Label_FieldId = new Guid("2716b337-82e7-4ecc-9f4c-12551e691ebe");
			public const string Submit_Button_Label_FieldName = "Submit Button Label";
			
			

	}


}
namespace Feature.GlobalSearch
{
	public static partial class Global_Search_Folder_Constants{

			public const string TemplateIdString = "d4bb6be0-df07-4d69-85d8-1c3ddec5f1dc";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Global Search Folder";

			

	}


}
