





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Feature.GenericCarousel
{
	public static partial class Generic_Carousel_Constants{

			public const string TemplateIdString = "5d9c34b5-e7c4-4f42-ab22-72e70b4b9e66";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Carousel";

			

	}


}
namespace Feature.GenericCarousel
{
	public static partial class Generic_Carousels_Folder_Constants{

			public const string TemplateIdString = "b1881da9-9c87-4923-8c29-a76176a254f1";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Carousels Folder";

			

	}


}
namespace Feature.GenericCarousel
{
	public static partial class Generic_Carousel_Slide_Constants{

			public const string TemplateIdString = "e203d890-8066-41cf-8883-810cc9f470ba";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Carousel Slide";

					
			public static readonly Guid Description_FieldId = new Guid("0955ab21-909f-4e1e-99ab-67a7e85c4468");
			public const string Description_FieldName = "Description";
			
					
			public static readonly Guid Image_FieldId = new Guid("34801875-5f9b-4d55-9ac7-84bff40c2892");
			public const string Image_FieldName = "Image";
			
					
			public static readonly Guid Link_FieldId = new Guid("2fa056f0-4986-4b3f-9a89-940cf60967cc");
			public const string Link_FieldName = "Link";
			
					
			public static readonly Guid Subtitle_FieldId = new Guid("09040d94-583b-42d9-af81-1a64a7c55b16");
			public const string Subtitle_FieldName = "Subtitle";
			
					
			public static readonly Guid Title_FieldId = new Guid("6a2802fc-6292-44e4-91fc-c0d59384b20b");
			public const string Title_FieldName = "Title";
			
			

	}


}
