





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Foundation.Site
{
	public static partial class _Site_Constants{

			public const string TemplateIdString = "dfa139e2-1c9e-48d3-b935-cb095e1f1371";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "_Site";

			

	}


}
